title: Teja Vayila
description: Embedded Firmware Engineer

url: "https://teja-core.github.io"
baseurl: ""

remote_theme: academicpages/academicpages.github.io
plugins:
  - jekyll-remote-theme

author:
  name: Teja Vayila
  avatar: /assets/images/profile.jpg
  bio: Embedded Firmware Engineer
  location: Mysore, India
  email: vayilateja789@gmail.com
